/**
 * Created by Nikhil on 1/8/2016.
 */
public class ExceptionPratice {
    public static void main(String[] args) {
        try {

        } catch (ArrayIndexOutOfBoundsException e) {
            e.getCause();
        } catch (Exception e) {

        }
    }
    void methode1() throws ArrayIndexOutOfBoundsException{

    }
}

